services:
  api:
    restart: unless-stopped
    network_mode: host
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: ${CONNECTION_STRING}
      Auth__ApiKey: ${Auth__ApiKey}

  db:
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  front:
    build:
      context: src/Stockly.Client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    extra_hosts:
      - "api:host-gateway"
