/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as PreparationIndexRouteImport } from './routes/preparation/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreLocationIdRouteImport } from './routes/store/$locationId'
import { Route as StockLocationIdRouteImport } from './routes/stock/$locationId'
import { Route as PreparationRecipesIndexRouteImport } from './routes/preparation/recipes/index'
import { Route as PreparationGroceryListIndexRouteImport } from './routes/preparation/grocery-list/index'
import { Route as AdminStockIndexRouteImport } from './routes/admin/stock/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminRecipesIndexRouteImport } from './routes/admin/recipes/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminLocationsIndexRouteImport } from './routes/admin/locations/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as PreparationRecipesRecipeIdRouteImport } from './routes/preparation/recipes/$recipeId'
import { Route as PreparationGroceryListPrepareRouteImport } from './routes/preparation/grocery-list/prepare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationIndexRoute = PreparationIndexRouteImport.update({
  id: '/preparation/',
  path: '/preparation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLocationIdRoute = StoreLocationIdRouteImport.update({
  id: '/store/$locationId',
  path: '/store/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const StockLocationIdRoute = StockLocationIdRouteImport.update({
  id: '/stock/$locationId',
  path: '/stock/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationRecipesIndexRoute = PreparationRecipesIndexRouteImport.update({
  id: '/preparation/recipes/',
  path: '/preparation/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationGroceryListIndexRoute =
  PreparationGroceryListIndexRouteImport.update({
    id: '/preparation/grocery-list/',
    path: '/preparation/grocery-list/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminStockIndexRoute = AdminStockIndexRouteImport.update({
  id: '/admin/stock/',
  path: '/admin/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecipesIndexRoute = AdminRecipesIndexRouteImport.update({
  id: '/admin/recipes/',
  path: '/admin/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsIndexRoute = AdminLocationsIndexRouteImport.update({
  id: '/admin/locations/',
  path: '/admin/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/admin/categories/',
  path: '/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationRecipesRecipeIdRoute =
  PreparationRecipesRecipeIdRouteImport.update({
    id: '/preparation/recipes/$recipeId',
    path: '/preparation/recipes/$recipeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreparationGroceryListPrepareRoute =
  PreparationGroceryListPrepareRouteImport.update({
    id: '/preparation/grocery-list/prepare',
    path: '/preparation/grocery-list/prepare',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stock/$locationId': typeof StockLocationIdRoute
  '/store/$locationId': typeof StoreLocationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/preparation/': typeof PreparationIndexRoute
  '/stock/': typeof StockIndexRoute
  '/store/': typeof StoreIndexRoute
  '/preparation/grocery-list/prepare': typeof PreparationGroceryListPrepareRoute
  '/preparation/recipes/$recipeId': typeof PreparationRecipesRecipeIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/stock/': typeof AdminStockIndexRoute
  '/preparation/grocery-list/': typeof PreparationGroceryListIndexRoute
  '/preparation/recipes/': typeof PreparationRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stock/$locationId': typeof StockLocationIdRoute
  '/store/$locationId': typeof StoreLocationIdRoute
  '/admin': typeof AdminIndexRoute
  '/preparation': typeof PreparationIndexRoute
  '/stock': typeof StockIndexRoute
  '/store': typeof StoreIndexRoute
  '/preparation/grocery-list/prepare': typeof PreparationGroceryListPrepareRoute
  '/preparation/recipes/$recipeId': typeof PreparationRecipesRecipeIdRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/recipes': typeof AdminRecipesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/stock': typeof AdminStockIndexRoute
  '/preparation/grocery-list': typeof PreparationGroceryListIndexRoute
  '/preparation/recipes': typeof PreparationRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stock/$locationId': typeof StockLocationIdRoute
  '/store/$locationId': typeof StoreLocationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/preparation/': typeof PreparationIndexRoute
  '/stock/': typeof StockIndexRoute
  '/store/': typeof StoreIndexRoute
  '/preparation/grocery-list/prepare': typeof PreparationGroceryListPrepareRoute
  '/preparation/recipes/$recipeId': typeof PreparationRecipesRecipeIdRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/recipes/': typeof AdminRecipesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/stock/': typeof AdminStockIndexRoute
  '/preparation/grocery-list/': typeof PreparationGroceryListIndexRoute
  '/preparation/recipes/': typeof PreparationRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stock/$locationId'
    | '/store/$locationId'
    | '/admin/'
    | '/preparation/'
    | '/stock/'
    | '/store/'
    | '/preparation/grocery-list/prepare'
    | '/preparation/recipes/$recipeId'
    | '/admin/categories/'
    | '/admin/locations/'
    | '/admin/products/'
    | '/admin/recipes/'
    | '/admin/settings/'
    | '/admin/stock/'
    | '/preparation/grocery-list/'
    | '/preparation/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stock/$locationId'
    | '/store/$locationId'
    | '/admin'
    | '/preparation'
    | '/stock'
    | '/store'
    | '/preparation/grocery-list/prepare'
    | '/preparation/recipes/$recipeId'
    | '/admin/categories'
    | '/admin/locations'
    | '/admin/products'
    | '/admin/recipes'
    | '/admin/settings'
    | '/admin/stock'
    | '/preparation/grocery-list'
    | '/preparation/recipes'
  id:
    | '__root__'
    | '/'
    | '/stock/$locationId'
    | '/store/$locationId'
    | '/admin/'
    | '/preparation/'
    | '/stock/'
    | '/store/'
    | '/preparation/grocery-list/prepare'
    | '/preparation/recipes/$recipeId'
    | '/admin/categories/'
    | '/admin/locations/'
    | '/admin/products/'
    | '/admin/recipes/'
    | '/admin/settings/'
    | '/admin/stock/'
    | '/preparation/grocery-list/'
    | '/preparation/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StockLocationIdRoute: typeof StockLocationIdRoute
  StoreLocationIdRoute: typeof StoreLocationIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PreparationIndexRoute: typeof PreparationIndexRoute
  StockIndexRoute: typeof StockIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  PreparationGroceryListPrepareRoute: typeof PreparationGroceryListPrepareRoute
  PreparationRecipesRecipeIdRoute: typeof PreparationRecipesRecipeIdRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminLocationsIndexRoute: typeof AdminLocationsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminRecipesIndexRoute: typeof AdminRecipesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminStockIndexRoute: typeof AdminStockIndexRoute
  PreparationGroceryListIndexRoute: typeof PreparationGroceryListIndexRoute
  PreparationRecipesIndexRoute: typeof PreparationRecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/': {
      id: '/preparation/'
      path: '/preparation'
      fullPath: '/preparation/'
      preLoaderRoute: typeof PreparationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$locationId': {
      id: '/store/$locationId'
      path: '/store/$locationId'
      fullPath: '/store/$locationId'
      preLoaderRoute: typeof StoreLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$locationId': {
      id: '/stock/$locationId'
      path: '/stock/$locationId'
      fullPath: '/stock/$locationId'
      preLoaderRoute: typeof StockLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/recipes/': {
      id: '/preparation/recipes/'
      path: '/preparation/recipes'
      fullPath: '/preparation/recipes/'
      preLoaderRoute: typeof PreparationRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/grocery-list/': {
      id: '/preparation/grocery-list/'
      path: '/preparation/grocery-list'
      fullPath: '/preparation/grocery-list/'
      preLoaderRoute: typeof PreparationGroceryListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock/': {
      id: '/admin/stock/'
      path: '/admin/stock'
      fullPath: '/admin/stock/'
      preLoaderRoute: typeof AdminStockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recipes/': {
      id: '/admin/recipes/'
      path: '/admin/recipes'
      fullPath: '/admin/recipes/'
      preLoaderRoute: typeof AdminRecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations/': {
      id: '/admin/locations/'
      path: '/admin/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof AdminLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/recipes/$recipeId': {
      id: '/preparation/recipes/$recipeId'
      path: '/preparation/recipes/$recipeId'
      fullPath: '/preparation/recipes/$recipeId'
      preLoaderRoute: typeof PreparationRecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation/grocery-list/prepare': {
      id: '/preparation/grocery-list/prepare'
      path: '/preparation/grocery-list/prepare'
      fullPath: '/preparation/grocery-list/prepare'
      preLoaderRoute: typeof PreparationGroceryListPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StockLocationIdRoute: StockLocationIdRoute,
  StoreLocationIdRoute: StoreLocationIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  PreparationIndexRoute: PreparationIndexRoute,
  StockIndexRoute: StockIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  PreparationGroceryListPrepareRoute: PreparationGroceryListPrepareRoute,
  PreparationRecipesRecipeIdRoute: PreparationRecipesRecipeIdRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminLocationsIndexRoute: AdminLocationsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminRecipesIndexRoute: AdminRecipesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminStockIndexRoute: AdminStockIndexRoute,
  PreparationGroceryListIndexRoute: PreparationGroceryListIndexRoute,
  PreparationRecipesIndexRoute: PreparationRecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
